package com.financebot.telegrambot.intent;

public enum TelegramIntentType {
    UNKNOWN,
    CREATE_EXPENSE,
    CREATE_INSTALLMENT_EXPENSE,
    CREATE_INCOME,
    QUERY_MONTH_EXPENSE_TOTAL,
    QUERY_MONTH_INCOME_TOTAL,
    QUERY_MONTH_ANALYSIS,
    QUERY_TRANSACTION_TOTAL,
    QUERY_INSTALLMENT_COUNT,
    QUERY_INSTALLMENT_PURCHASE_CAPACITY,
    QUERY_INSTALLMENT_REMAINING,
    QUERY_ACTIVE_INSTALLMENTS,
    QUERY_INSTALLMENT_END_DATE
}
