global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: financebot-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [financebot-backend:8082]

  - job_name: financebot-telegram-bot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [financebot-telegram-bot:8083]
